version: '3'

services:
  db:
    image: mysql:5.7
    container_name: moodle-block_steps_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpw
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: moodle-block_steps_website
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/moodle/blocks/steps
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
